version: '3.8'

services:
  nomic_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_SERVICE_URL=http://db_service:8001
    depends_on:
      - db_service
      - db
    command: >
      sh -c "pip install uvicorn && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  db_service:
    build: ./db_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/embeddings
    depends_on:
      - db

  db:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=embeddings
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 