version: '3.8'

services:
  nomic_service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NOMIC_API_KEY=${NOMIC_API_KEY}
      - DB_SERVICE_URL=http://db_service:8001
    depends_on:
      - db_service

  db_service:
    build: ./db_service
    ports:
      - "8001:8001"
    environment:
      - DB_DIR=/app/data
      - DB_NAME=embeddings.db
    volumes:
      - db_data:/app/data

volumes:
  db_data: 