version: '3.8'

services:
  nomic_service:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NOMIC_API_KEY=${NOMIC_API_KEY}
      - DB_SERVICE_URL=http://db_service:8001
    depends_on:
      - db_service
      - db

  db_service:
    build: ./db_service
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5433/embeddings
    depends_on:
      - db

  db:
    image: ankane/pgvector:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=embeddings
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 